### ISSUE TITLE
Unsupported operation: Infinity or NaN toInt

### ISSUE THREAD

**Issue by egnimos** [r-mzy47/candlesticks#10]
I'am running the latest version of the "candlestick" package every time I load the data from the API, getting this error ::

![Screenshot 2022-03-09 105003](https://user-images.githubusercontent.com/54541657/157378014-a856f62a-edf3-42d1-b7ec-97eced8cde3e.png)

please can you help me in this

**Comment by r-mzy47** [comment]
could you please provide some code snippets so I can regenerate this exception?

**Comment by caokietbk** [comment]
![image](https://user-images.githubusercontent.com/45527841/157788078-6cb3bba1-2bfd-404a-9b5a-49968fea96ce.png)
I have the same problem.
When I debug, I discover that HelperFunctions.log10(minStepSize) with minStepSize = 0 (when high = low) will return negative infinity. So that exception was thrown.

mobile_chart.dart line 68-69

**Comment by r-mzy47** [comment]
@caokietbk high is the maximum of all visible candles-high. and low is the minimum of all visible candles-low. so these values shouldn't be equal. So you will be very kind if you provide some code and your candles data so I can regenerate this exception.

**Comment by caokietbk** [comment]
I can't reproduce this error. Perhaps there is an issue with the API data. Thank you very much for a great library and your support.
